
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

# -------------------------------
# Load Training Dataset
# -------------------------------

data = pd.read_csv("dataset.csv")

X = data[[
    "OCR_Confidence",
    "Truth_Table_Accuracy",
    "Average_Input_Voltage",
    "Average_Output_Voltage",
    "Voltage_Drop",
    "Failed_Logic_Tests"
]]

y = data["Label"]

# -------------------------------
# Train Model
# -------------------------------

model = DecisionTreeClassifier(random_state=42)

model.fit(X, y)

# -------------------------------
# Example Feature Vector
# (Normally generated by
# feature_extraction.py)
# -------------------------------

sample = [[

    98.4,   # OCR Confidence

    100,    # Truth Table Accuracy

    5.00,   # Average Input Voltage

    4.98,   # Average Output Voltage

    0.02,   # Voltage Drop

    0        # Failed Logic Tests

]]

prediction = model.predict(sample)

print("Prediction:", prediction[0])
